// Mocks generated by Mockito 5.1.0 from annotations
// in clean_code/test/modules/auth/domain/use_cases/login_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:clean_code/core/error/failure.dart' as _i5;
import 'package:clean_code/modules/authentication/domain/entities/user_entity.dart'
    as _i6;
import 'package:clean_code/modules/authentication/domain/repository/user_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeOption_1<A> extends _i1.Fake implements _i2.Option<A> {}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> login(
          {String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#login, [], {#email: email, #password: password}),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.UserEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> register(
          {String? name, String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #register, [], {#name: name, #email: email, #password: password}),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.UserEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);
  @override
  _i4.Future<_i2.Option<_i5.Failure>> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
              returnValue: Future<_i2.Option<_i5.Failure>>.value(
                  _FakeOption_1<_i5.Failure>()))
          as _i4.Future<_i2.Option<_i5.Failure>>);
}
